RegistroEmpleado/Models/User.cs
namespace RegistroEmpleado.Models
{
    public class User
    {
        public int Id { get; set; }
        public int Cedula { get; set; }
        public int TipoUser { get; set; }
        public string? Email { get; set; }
        public string? Phone { get; set; }
        public string? Names { get; set; }
        public string? LastNames { get; set; }
        public string? PhotoProfile { get; set; }
        public string? Password { get; set; }

    }
}

RegistroEmpleado/Controllers/AdminsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using RegistroEmpleado.Models;
using RegistroEmpleado.Data;

namespace RegistroEmpleado.Controllers;

[Authorize(Roles = "Admin")]
public class AdminsController : Controller
{
    private readonly BaseContext _context;

    public AdminsController(BaseContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        var idUserLog = int.Parse(HttpContext.Session.GetString("UserLog") ?? string.Empty);
        var idRecord = _context.TimeRegisters.Where(t => t.IdUser == idUserLog).OrderByDescending(m => m.Id ).First().Id;
        HttpContext.Session.SetString("RecordUser", idRecord.ToString());
        return View();
    }

    public async Task<IActionResult> Manage()
    {
        return View(await _context.Users.ToListAsync());
    }

    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(User user)
    {
        user.PhotoProfile = "User.svg";
        user.TipoUser = 2;
        _context.Users.Add(user);
        _context.SaveChanges();
        return RedirectToAction("Manage");
    }

    //Eliminar

    public async Task<IActionResult> Delete(int id)
    {
        var user = await _context.Users.FirstOrDefaultAsync(m => m.Id == id);
        return View(user);
    }

    public async Task<IActionResult> DeleteUser(int id)
    {
        var user = await _context.Users.FindAsync(id);
        _context.Users.Remove(user);
        await _context.SaveChangesAsync();
        return RedirectToAction("Manage");
    }


    public async Task<IActionResult> Record(int id)
    {
        var timeRegisters = await _context.TimeRegisters.Where(m => m.IdUser == id).ToListAsync();
        return View(timeRegisters);
    }
}

RegistroEmpleado/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RegistroEmpleado.Data;
using RegistroEmpleado.Helpers;
using RegistroEmpleado.Providers;
using RegistroEmpleado.Models;
using Microsoft.EntityFrameworkCore;

namespace RegistroEmpleado.Controllers;

[Authorize(Roles = "Employee")]
public class UsersController : Controller
{
    private readonly BaseContext _context;
    private readonly HelperUploadFiles _helperUploadFiles;

    public UsersController(BaseContext context, HelperUploadFiles helperUpload)
    {
        _context = context;
        _helperUploadFiles = helperUpload;
    }

    public IActionResult Index()
    {
            var idUserLog = int.Parse(HttpContext.Session.GetString("UserLog"));
            var user = _context.Users.First(u => u.Id == idUserLog);
            var idRecord = _context.TimeRegisters.Where(t => t.IdUser == idUserLog).OrderByDescending(m => m.Id ).First().Id;
            HttpContext.Session.SetString("RecordUser", idRecord.ToString());
        
        return View(user);
    }

  

        [HttpPost]
public async Task<IActionResult> Insert(IFormFile archivo)
{
    if (archivo == null || archivo.Length == 0)
    {
        return RedirectToAction("Profile");
    }

    string nombreArchivo = archivo.FileName;
    string path = await _helperUploadFiles.UploadFilesAsync(archivo, nombreArchivo);

    var idUserLog = int.Parse(HttpContext.Session.GetString("UserLog"));
    var user = _context.Users.First(u => u.Id == idUserLog);
    user.PhotoProfile = nombreArchivo;
    await _context.SaveChangesAsync();

    return RedirectToAction("Profile");
}


        public async Task<IActionResult> Record(int id)
        {
            var timeRegisters = await _context.TimeRegisters.Where(m => m.IdUser == id).ToListAsync();
            return View(timeRegisters);
        }

        public async Task<IActionResult> Profile(int id)
        {
            return View(await _context.Users.FirstOrDefaultAsync(m => m.Id == id)); 
        }
        
}

RegistroEmpleado/Views/Users/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
    ViewBag.Favicon = "Home.svg";
}

@section Home
{
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Index"><img src="~/img/Dasboard.svg"/> Home</a>
    </li>
}

@section Session
{
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Profile">Hello @Model.Names!! <img src="~/img/@Model.PhotoProfile" class="m-1" style="width: 20px"/></a>
    </li>
}

<div class="text-center">
    <h1 class="display-4">Welcome @Model.Names</h1>
</div>

  
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Control de Acceso</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Perfil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Record</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Cerrar Sesión</a>
      </li>
    </ul>
  </div>
</nav>

  <div class="container mt-4">
    <div class="jumbotron">
      <h1 class="display-4">Bienvenido al Sistema de Control de Acceso</h1>
      <p class="lead">Este sistema le permite a los usuarios realizar un seguimiento de sus horas de entrada y salida, así como ver y actualizar su información personal.</p>
      <hr class="my-4">
      <p>
      <a class="btn btn-primary btn-lg" role="button" asp-controller="Login" asp-action="Logout">Cerrar Sesión</a>
    </div>
  </div>

RegistroEmpleado/Views/Users/Profile.cshtml
@model User

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <style>
        .profile-picture {
            max-width: 200px;
            max-height: 400px;
            width: auto;
            height: auto;
        }
    </style>
</head>

<body>
    <div class="d-flex">
        <div>
            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Profile">
                Hello @Model.Names!!
                @if (Model.PhotoProfile != null)
                {
                    <img src="~/img/@Model.PhotoProfile" class="m-1 profile-picture" style="max-width: 50px; max-height: 50px;">
                }
            </a>

            @if (Model.PhotoProfile != null)
            {
                <img src="~/images/@Model.PhotoProfile" alt="Profile Picture" class="profile-picture">
            }
            else
            {
                <p>No profile picture available.</p>
            }

            <ul>
                <li>
                    <a asp-area="" asp-controller="Users" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                </li>
            </ul>

           @*  <div>
                <h1>Upload Profile Picture</h1>
                <form asp-action="Insert" method="post" enctype="multipart/form-data">
                    <div>
                        <label asp-for="PhotoProfile">Profile Picture:</label>
                        <input type="file" name="archivo">
                    </div>
                    <button type="submit">Upload</button>
                </form>
            </div> *@
        </div>

        <div>
            <h1>@Model.Names @Model.LastNames</h1>
            <h3>@Model.Cedula</h3>
            <p>@Model.Email</p>
            <p>@Model.Phone</p>
        </div>
    </div>
</body>

</html>

RegistroEmpleado/Views/Users/Record.cshtml
@{
    ViewData["Title"] = "Record";
}

@section Home
{
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Admins" asp-action="Index"><img src="~/img/Dasboard.svg"/> Home</a>
    </li>
}

@section Session
{
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Logout"><img src="~/img/Logout.svg" class="m-1"/>Logout</a>
    </li>
}

<table class="table  table-bordered mt-5 text-center table-striped table-hover">
    <thead class="table table-black">
        <tr>
            <th>Record</th>
        </tr>
        <tr>
            <td>Id</td>
            <td>LoginAt</td>
            <td>LogOffAt</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var Register in Model)
        {
            <tr>
                <td>@Register.Id</td>
                <td>@Register.LoginAt</td>
                <td>@Register.LogoutAt</td>
            </tr>
        }
    </tbody>
</table>